### PR TITLE
fix(toolkit-cleaner): missing cloudformation:ListStacks permission

### LINKED ISSUE #215: Missing ListStacks permission
Hello!

I just deployed this stack into my App Stack and the Step Functions is failing with the following error:

```
is not authorized to perform: cloudformation:ListStacks on resource: arn:aws:cloudformation:us-east-1:XXX:stack/*/* because no identity-based policy allows the cloudformation:ListStacks action
```

If manually added the permisson and it seems to work propertly. Any idea if I am doing something wrong? If not, is it ok to send a PR with this fix?

### PR DESCRIPTION
**Pull request by mdesanti**
Fixes #215

### CODE REVIEW

**Comment by jogold** [comment]
Really strange because it's the `DescribeStacks` API that is used...

**Comment by jogold** [comment]
Also it runs fine in my account (at least yesterday it did). Need to investigate.

**Comment by mdesanti** [comment]
@jogold full stacktrace below:

```
{
  "errorType": "AccessDenied",
  "errorMessage": "User: arn:aws:sts::XXX:assumed-role/mystack-CleaupUnusedAssetsGetStackNamesFuncti-BUZOMS9NRN85/mystack-CleaupUnusedAssetsGetStackNamesFuncti-BBDs53ykwwdG is not authorized to perform: cloudformation:ListStacks on resource: arn:aws:cloudformation:us-east-1:XXX:stack/*/* because no identity-based policy allows the cloudformation:ListStacks action",
  "trace": [
    "AccessDenied: User: arn:aws:sts::XXX:assumed-role/mystack-CleaupUnusedAssetsGetStackNamesFuncti-BUZOMS9NRN85/mystack-CleaupUnusedAssetsGetStackNamesFuncti-BBDs53ykwwdG is not authorized to perform: cloudformation:ListStacks on resource: arn:aws:cloudformation:us-east-1:XXX:stack/*/* because no identity-based policy allows the cloudformation:ListStacks action",
    "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:50:29)",
    "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
    "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
    "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
    "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
    "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
    "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
    "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
    "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)",
    "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
  ]
}
```

**Comment by mdesanti** [comment]
@jogold going through AWS' documentation I found the following: 

https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DescribeStacks.html

image

It looks like describe stacks uses list stacks under the hood if no Stack Name is passed as parameter

**Review by jogold — APPROVED** [review]
Really strange, something must have changed on the AWS side here... The construct is "widely" used for more than a year without any IAM permissions issues. Maybe something that is now enforced for new AWS accounts? Anyway I'm going to merge this now. Thanks @mdesanti.

**Comment by joeflateau** [comment]
Here's the message I got from AWS this AM regarding this issue:

On January 25, 2023, we updated our DescribeStacks API as part of our continuous improvements to ensure customers have granular control over the APIs they use.

We require your action to update IAM Policies in your account by March 27, 2023 to avoid disruption to your DescribeStacks API calls.

AWS CloudFormation now requires that customers have the cloudformation:ListStacks permission when calling DescribeStacks[1] without a target stack. This is in addition to the cloudformation:DescribeStacks permission that is already a requirement. You will need to add the cloudformation:ListStacks permission by March 27, 2023, on any calling principles using the DescribeStacks API without a target. CloudFormation has identified principals associated with your account that do not have ListStacks permissions making DescribeStacks calls without a target. The users or roles listed in the 'Affected resources' tab need their policies updated to include cloudformation:ListStacks along with the existing cloudformation:DescribeStacks permissions.

**Comment by jogold** [comment]
Thanks @joeflateau, got the same this morning. I knew something had changed on the AWS side 😄

**Pull request merged**
